### ISSUE TITLE
Fix IllegalStateException

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kotter#66]
Getting this occasionally when exiting an app using Kotter:

```
Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
Otherwise, a callback/listener may leak in case of external cancellation.
See callbackFlow API documentation for the details.
	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:362)
	at kotlinx.coroutines.flow.CallbackFlowBuilder$collectTo$1.invokeSuspend(Builders.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by bitspittle** [comment]
I'm not sure I've seen this in a while. I'll close this for now but can always reopen / refile later.
